imports:
    - { resource: tables.yml }

services:
    phpbb.autogroups.listener:
        class: phpbb\autogroups\event\listener
        arguments:
            - @phpbb.autogroups.manager
        tags:
            - { name: event.listener }

    phpbb.autogroups.manager:
        class: phpbb\autogroups\conditions\manager
        arguments:
            - @phpbb.autogroups.type_collection
            - @service_container
            - @dbal.conn
            - @user
            - %phpbb.autogroups.tables.autogroups_rules%
            - %phpbb.autogroups.tables.autogroups_types%

# ----- Auto groups types -----
# Scope MUST be prototype for all the plugins to work.
    phpbb.autogroups.type_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: phpbb.autogroups.type }

    phpbb.autogroups.type.posts:
        class: phpbb\autogroups\conditions\type\posts
        scope: prototype
        arguments:
            - @service_container
            - @config
            - @dbal.conn
            - @user
            - %phpbb.autogroups.tables.autogroups_rules%
            - %phpbb.autogroups.tables.autogroups_types%
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: phpbb.autogroups.type }

    phpbb.autogroups.type.warnings:
        class: phpbb\autogroups\conditions\type\warnings
        scope: prototype
        arguments:
            - @service_container
            - @config
            - @dbal.conn
            - @user
            - %phpbb.autogroups.tables.autogroups_rules%
            - %phpbb.autogroups.tables.autogroups_types%
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: phpbb.autogroups.type }

    phpbb.autogroups.type.membership:
        class: phpbb\autogroups\conditions\type\membership
        scope: prototype
        arguments:
            - @service_container
            - @config
            - @dbal.conn
            - @user
            - %phpbb.autogroups.tables.autogroups_rules%
            - %phpbb.autogroups.tables.autogroups_types%
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: phpbb.autogroups.type }

    phpbb.autogroups.notification.type.group_added:
        class: phpbb\autogroups\notification\type\group_added
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    phpbb.autogroups.notification.type.group_removed:
        class: phpbb\autogroups\notification\type\group_removed
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    phpbb.autogroups.cron.task.autogroups_check:
        class: phpbb\autogroups\cron\autogroups_check
        arguments:
            - @config
            - @phpbb.autogroups.manager
        calls:
            - [set_name, [cron.task.autogroups_check]]
        tags:
            - { name: cron.task }
